### ISSUE TITLE
Use new identifiers for VSCode 1.43+ 

### ISSUE THREAD

**Issue by artaommahe** [perragnar/september-steel#5]
VSCode changed default highlighting identifiers so by default some stuff looks wrong now.
https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting

**Comment by perragnar** [comment]
Oh, I see.. Is this only a typescript thing?

**Comment by artaommahe** [comment]
html/scss looks fine for me

**Comment by perragnar** [comment]
It seems like the latest vscode update defaults the semantic highlighting to false again, so things should look right again.
_But_ this will be set to true again later on så I will look into the new semantic highlighting thing to make use of it, since I think it will be a great update to theming.

Closing this for now. Thanks for letting me know about the issue by the way!
